// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soidedmnptykakwegozy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvaWRlZG1ucHR5a2Frd2Vnb3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MzY0NjMsImV4cCI6MjA1OTAxMjQ2M30.L8eTCSRkMk5ENZ6xo8ExMdjFWUr8Tcuzhv7mQNBKuEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);